name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Add Upstream and Sync
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote add upstream https://github.com/Thxssio/VSSS_PROJECT.git
          git fetch upstream
          git checkout main
          git reset --hard upstream/main # Garante que o fork fique igual ao repositório original
          git push origin main --force # Força a atualização do fork
